import sys
import argparse
from decimal import Decimal
from datetime import datetime
from pathlib import Path

# Resolve to backend/ regardless of where the script is invoked from
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from app.core.database import SessionLocal
    from app.models import models
except ImportError:
    print("Error: Could not import backend modules. Run this from the project root.")
    sys.exit(1)

def fix_wallet_pollution(dry_run=True):
    db = SessionLocal()
    mode = "DRY RUN (Viewing changes only)" if dry_run else "EXECUTION (Modifying DB)"
    print(f"--- FTTH Wallet Correction Started: {mode} ---")
    
    try:
        # Target only FTTH activation expenses generated by the previous logic bug
        # Pattern used in faulty logic: f"تفعيل اشتراك - {name}"
        pollution_query = db.query(models.WalletTransaction).filter(
            models.WalletTransaction.wallet_type == 'ftth',
            models.WalletTransaction.type == 'expense',
            models.WalletTransaction.description.like('تفعيل اشتراك - %')
        )
        
        pollution_records = pollution_query.all()
        count = len(pollution_records)
        total_amount = sum(r.amount for r in pollution_records)
        
        print(f"Found {count} incorrect FTTH activation transactions.")
        print(f"Total polluted amount to be reversed: {total_amount:,.2f} IQD")
        
        if count == 0:
            print("No pollution found. FTTH wallet is already clean.")
            return

        for record in pollution_records:
            print(f"[{'SKIP' if dry_run else 'DELETE'}] ID: {record.id} | Desc: {record.description} | Amt: {record.amount:,.0f}")
            if not dry_run:
                db.delete(record)
        
        if not dry_run:
            db.commit()
            print(f"\nSUCCESS: Corrected FTTH wallet. {count} records deleted.")
        else:
            print(f"\nDRY RUN COMPLETE: No changes were made. Found {count} records to delete.")
        
        # Verify result logic
        final_query = db.query(models.WalletTransaction).filter(models.WalletTransaction.wallet_type == 'ftth')
        recharges = sum(r.amount for r in final_query.filter(models.WalletTransaction.type == 'recharge').all())
        expenses = sum(r.amount for r in final_query.filter(models.WalletTransaction.type == 'expense').all())
        print(f"FTTH Wallet Summary (After fix if executed):")
        print(f"  - Total Recharges (Legitimate funding): {recharges:,.2f} IQD")
        print(f"  - Total Remaining Expenses: {expenses:,.2f} IQD")
        print(f"  - Predicted Balance: {recharges - expenses:,.2f} IQD")

    except Exception as e:
        print(f"FATAL ERROR: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Clean up FTTH wallet pollution caused by activation logic bug.")
    parser.add_argument("--execute", action="store_true", help="Actually perform the deletion. Without this, it runs in dry-run mode.")
    args = parser.parse_args()
    
    fix_wallet_pollution(dry_run=not args.execute)
