"""add_message_templates_and_office_debt_reminder

Revision ID: 20bb3b17bc42
Revises: fa48c28e13b4
Create Date: 2026-04-07 16:07:31.113786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20bb3b17bc42'
down_revision: Union[str, None] = 'fa48c28e13b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_index(op.f('ix_message_templates_key'), 'message_templates', ['key'], unique=True)
    op.drop_index(op.f('ix_activity_log_created_at'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_section'), table_name='activity_log')
    op.create_foreign_key(None, 'activity_log', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('card_purchases', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_card_purchases_id'), 'card_purchases', ['id'], unique=False)
    op.alter_column('card_sales', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_card_sales_id'), 'card_sales', ['id'], unique=False)
    op.alter_column('card_wallet_transactions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_card_wallet_transactions_id'), 'card_wallet_transactions', ['id'], unique=False)
    op.alter_column('ftth_customers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ftth_customers', 'external_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ftth_customers', 'source_system',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("'ftth_portal'::text"))
    op.alter_column('ftth_customers', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ftth_customers', 'import_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('ftth_customers', 'customer_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'secondary_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'governorate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'district',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'sub_district',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'gps_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=8),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'gps_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=8),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'subscription_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'zone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'bundle',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'onu_username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'onu_serial',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'fdt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'fat',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'mac_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('ftth_customers_external_customer_id_key'), 'ftth_customers', type_='unique')
    op.drop_index(op.f('idx_ftth_customers_external_customer_id'), table_name='ftth_customers')
    op.drop_index(op.f('idx_ftth_customers_subscriber_id'), table_name='ftth_customers')
    op.drop_constraint(op.f('unique_external_id'), 'ftth_customers', type_='unique')
    op.create_index(op.f('ix_ftth_customers_external_customer_id'), 'ftth_customers', ['external_customer_id'], unique=True)
    op.create_index(op.f('ix_ftth_customers_subscriber_id'), 'ftth_customers', ['subscriber_id'], unique=False)
    op.drop_column('ftth_customers', 'street')
    op.drop_column('ftth_customers', 'house')
    op.drop_column('ftth_customers', 'usr_referral_code')
    op.drop_column('ftth_customers', 'updated_at')
    op.drop_column('ftth_customers', 'is_pending')
    op.drop_column('ftth_customers', 'neighborhood')
    op.drop_column('ftth_customers', 'partner_name')
    op.alter_column('ftth_external_data', 'governorate',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'district',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'neighborhood',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'street',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'house',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'gps_latitude',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'gps_longitude',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'onu_serial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'partner_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('ftth_external_data_external_customer_id_key'), 'ftth_external_data', type_='unique')
    op.drop_constraint(op.f('ftth_external_data_external_id_key'), 'ftth_external_data', type_='unique')
    op.drop_index(op.f('idx_ftth_external_data_external_id'), table_name='ftth_external_data')
    op.drop_index(op.f('idx_ftth_external_data_imported_subscriber_id'), table_name='ftth_external_data')
    op.drop_index(op.f('ix_ftth_external_data_imported'), table_name='ftth_external_data')
    op.drop_index(op.f('ix_ftth_external_data_national_name'), table_name='ftth_external_data')
    op.drop_constraint(op.f('unique_external_id_main'), 'ftth_external_data', type_='unique')
    op.drop_index(op.f('ux_ftth_external_data_external_id'), table_name='ftth_external_data')
    op.drop_column('ftth_external_data', 'external_customer_id')
    op.drop_column('ftth_external_data', 'subscription_end_date')
    op.drop_column('ftth_external_data', 'onu_username')
    op.drop_column('ftth_external_data', 'subscription_start_date')
    op.drop_column('ftth_external_data', 'subscription_status')
    op.drop_column('ftth_external_data', 'full_name')
    op.alter_column('ftth_sync_run_items', 'external_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ftth_sync_run_items', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.create_index(op.f('ix_ftth_sync_run_items_external_customer_id'), 'ftth_sync_run_items', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_ftth_sync_run_items_ftth_external_data_id'), 'ftth_sync_run_items', ['ftth_external_data_id'], unique=False)
    op.create_index(op.f('ix_ftth_sync_run_items_sync_run_id'), 'ftth_sync_run_items', ['sync_run_id'], unique=False)
    op.drop_column('ftth_sync_run_items', 'action_taken')
    op.drop_column('ftth_sync_run_items', 'message')
    op.drop_column('ftth_sync_run_items', 'ftth_customer_id')
    op.drop_column('ftth_sync_run_items', 'subscriber_id')
    op.drop_column('ftth_sync_run_items', 'created_at')
    op.alter_column('ftth_sync_runs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::text"))
    op.create_index(op.f('ix_ftth_sync_runs_portal_config_id'), 'ftth_sync_runs', ['portal_config_id'], unique=False)
    op.drop_column('ftth_sync_runs', 'total_fetched')
    op.drop_column('ftth_sync_runs', 'total_updated')
    op.drop_column('ftth_sync_runs', 'total_failed')
    op.drop_column('ftth_sync_runs', 'total_created')
    op.drop_column('ftth_sync_runs', 'error_summary')
    op.drop_column('ftth_sync_runs', 'sync_type')
    op.drop_column('ftth_sync_runs', 'total_linked')
    op.drop_index(op.f('ux_internet_phones_phone_number'), table_name='internet_phones')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('office_customers', sa.Column('last_debt_reminder_date', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ux_office_invoices_invoice_no'), table_name='office_invoices')
    op.create_index(op.f('ix_subscriber_debt_entries_id'), 'subscriber_debt_entries', ['id'], unique=False)
    op.drop_index(op.f('ux_subscribers_telegram_chat_id'), table_name='subscribers', postgresql_where='(telegram_chat_id IS NOT NULL)')
    op.drop_index(op.f('ux_subscribers_user_code'), table_name='subscribers')
    op.drop_constraint(op.f('fk_subscribers_fat'), 'subscribers', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscribers_zone'), 'subscribers', type_='foreignkey')
    op.create_foreign_key(None, 'subscribers', 'internet_zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'subscribers', 'internet_fats', ['fat_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscribers_zone'), 'subscribers', 'internet_zones', ['zone_id'], ['id'])
    op.create_foreign_key(op.f('fk_subscribers_fat'), 'subscribers', 'internet_fats', ['fat_id'], ['id'])
    op.create_index(op.f('ux_subscribers_user_code'), 'subscribers', ['user_code'], unique=True)
    op.create_index(op.f('ux_subscribers_telegram_chat_id'), 'subscribers', ['telegram_chat_id'], unique=True, postgresql_where='(telegram_chat_id IS NOT NULL)')
    op.drop_index(op.f('ix_subscriber_debt_entries_id'), table_name='subscriber_debt_entries')
    op.create_index(op.f('ux_office_invoices_invoice_no'), 'office_invoices', ['invoice_no'], unique=True)
    op.drop_column('office_customers', 'last_debt_reminder_date')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ux_internet_phones_phone_number'), 'internet_phones', ['phone_number'], unique=True)
    op.add_column('ftth_sync_runs', sa.Column('total_linked', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_runs', sa.Column('sync_type', sa.TEXT(), server_default=sa.text("'full'::text"), autoincrement=False, nullable=False))
    op.add_column('ftth_sync_runs', sa.Column('error_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_runs', sa.Column('total_created', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_runs', sa.Column('total_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_runs', sa.Column('total_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_runs', sa.Column('total_fetched', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ftth_sync_runs_portal_config_id'), table_name='ftth_sync_runs')
    op.alter_column('ftth_sync_runs', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::text"))
    op.add_column('ftth_sync_run_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('ftth_sync_run_items', sa.Column('subscriber_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_run_items', sa.Column('ftth_customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_run_items', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_sync_run_items', sa.Column('action_taken', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ftth_sync_run_items_sync_run_id'), table_name='ftth_sync_run_items')
    op.drop_index(op.f('ix_ftth_sync_run_items_ftth_external_data_id'), table_name='ftth_sync_run_items')
    op.drop_index(op.f('ix_ftth_sync_run_items_external_customer_id'), table_name='ftth_sync_run_items')
    op.alter_column('ftth_sync_run_items', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('ftth_sync_run_items', 'external_customer_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('ftth_external_data', sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_external_data', sa.Column('subscription_status', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_external_data', sa.Column('subscription_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ftth_external_data', sa.Column('onu_username', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_external_data', sa.Column('subscription_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ftth_external_data', sa.Column('external_customer_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ux_ftth_external_data_external_id'), 'ftth_external_data', ['external_id'], unique=True)
    op.create_unique_constraint(op.f('unique_external_id_main'), 'ftth_external_data', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ftth_external_data_national_name'), 'ftth_external_data', ['national_name'], unique=False)
    op.create_index(op.f('ix_ftth_external_data_imported'), 'ftth_external_data', ['imported_subscriber_id'], unique=False)
    op.create_index(op.f('idx_ftth_external_data_imported_subscriber_id'), 'ftth_external_data', ['imported_subscriber_id'], unique=False)
    op.create_index(op.f('idx_ftth_external_data_external_id'), 'ftth_external_data', ['external_id'], unique=False)
    op.create_unique_constraint(op.f('ftth_external_data_external_id_key'), 'ftth_external_data', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('ftth_external_data_external_customer_id_key'), 'ftth_external_data', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ftth_external_data', 'partner_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'onu_serial',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'gps_longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'gps_latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'house',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'street',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'neighborhood',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'district',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ftth_external_data', 'governorate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('ftth_customers', sa.Column('partner_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('neighborhood', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('is_pending', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('usr_referral_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('house', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ftth_customers', sa.Column('street', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ftth_customers_subscriber_id'), table_name='ftth_customers')
    op.drop_index(op.f('ix_ftth_customers_external_customer_id'), table_name='ftth_customers')
    op.create_unique_constraint(op.f('unique_external_id'), 'ftth_customers', ['external_customer_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ftth_customers_subscriber_id'), 'ftth_customers', ['subscriber_id'], unique=False)
    op.create_index(op.f('idx_ftth_customers_external_customer_id'), 'ftth_customers', ['external_customer_id'], unique=False)
    op.create_unique_constraint(op.f('ftth_customers_external_customer_id_key'), 'ftth_customers', ['external_customer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ftth_customers', 'mac_address',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'ip_address',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'fat',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'fdt',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'onu_serial',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'onu_username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'bundle',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'zone',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'subscription_status',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'gps_longitude',
               existing_type=sa.Numeric(precision=12, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'gps_latitude',
               existing_type=sa.Numeric(precision=12, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'sub_district',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'district',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'governorate',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'secondary_phone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'phone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'customer_type',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ftth_customers', 'import_status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('ftth_customers', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ftth_customers', 'source_system',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ftth_portal'::text"))
    op.alter_column('ftth_customers', 'external_customer_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('ftth_customers', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_card_wallet_transactions_id'), table_name='card_wallet_transactions')
    op.alter_column('card_wallet_transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_card_sales_id'), table_name='card_sales')
    op.alter_column('card_sales', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_card_purchases_id'), table_name='card_purchases')
    op.alter_column('card_purchases', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.create_index(op.f('ix_activity_log_section'), 'activity_log', ['section'], unique=False)
    op.create_index(op.f('ix_activity_log_created_at'), 'activity_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_message_templates_key'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
