"""complete_initial_schema

Revision ID: 46ea3fc3787a
Revises: 
Create Date: 2026-03-30 21:51:39.367527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ea3fc3787a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_purchases_id'), 'card_purchases', ['id'], unique=False)
    op.create_table('card_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_sales_id'), 'card_sales', ['id'], unique=False)
    op.create_table('card_wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_type', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_wallet_transactions_id'), 'card_wallet_transactions', ['id'], unique=False)
    op.create_table('cashback_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_history_id'), 'cashback_history', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('ftth_portal_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_url', sa.Text(), nullable=False),
    sa.Column('list_url', sa.Text(), nullable=True),
    sa.Column('username_enc', sa.LargeBinary(), nullable=False),
    sa.Column('password_enc', sa.LargeBinary(), nullable=False),
    sa.Column('parse_mode', sa.String(length=50), nullable=False),
    sa.Column('parse_options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_new', sa.Integer(), nullable=False),
    sa.Column('last_sync_updated', sa.Integer(), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ftth_portal_config_id'), 'ftth_portal_config', ['id'], unique=False)
    op.create_table('internet_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_internet_materials_id'), 'internet_materials', ['id'], unique=False)
    op.create_table('internet_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internet_phones_id'), 'internet_phones', ['id'], unique=False)
    op.create_index(op.f('ix_internet_phones_phone_number'), 'internet_phones', ['phone_number'], unique=True)
    op.create_table('internet_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_internet_zones_id'), 'internet_zones', ['id'], unique=False)
    op.create_table('office_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_customers_id'), 'office_customers', ['id'], unique=False)
    op.create_table('office_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_materials_id'), 'office_materials', ['id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('sim_inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_inventory_transactions_id'), 'sim_inventory_transactions', ['id'], unique=False)
    op.create_table('sim_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('topup_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('company_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('jb_return', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_packages_id'), 'sim_packages', ['id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_code', sa.String(length=100), nullable=True),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('national_id_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('fat', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('category_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('subscription_type', sa.String(length=50), nullable=True),
    sa.Column('debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subscription_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_subscribers_telegram_chat_id'), 'subscribers', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_subscribers_user_code'), 'subscribers', ['user_code'], unique=True)
    op.create_table('subscription_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_categories_id'), 'subscription_categories', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('outstanding_debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_alert_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_alert_threshold', sa.Integer(), nullable=False),
    sa.Column('earthlink_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('swig_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qi_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cards_threshold', sa.Integer(), nullable=False),
    sa.Column('materials_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=True),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('cards_report_name', sa.String(length=255), nullable=True),
    sa.Column('backup_storage_path', sa.Text(), nullable=True),
    sa.Column('backup_schedule', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('backup_schedule_time', sa.String(length=8), server_default='02:00', nullable=False),
    sa.Column('backup_schedule_weekday', sa.Integer(), nullable=True),
    sa.Column('backup_schedule_month_day', sa.Integer(), nullable=True),
    sa.Column('backup_last_scheduled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('recovery_email', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('reset_code', sa.String(length=10), nullable=True),
    sa.Column('reset_code_expiry', sa.DateTime(), nullable=True),
    sa.Column('requires_password_change', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wallet_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_activity_log_user_id'), 'activity_log', ['user_id'], unique=False)
    op.create_table('ftth_external_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('national_name', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=200), nullable=True),
    sa.Column('fat', sa.String(length=200), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('service_username', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remaining_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('imported_subscriber_id', sa.BigInteger(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_subscriber_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ftth_external_data_external_id'), 'ftth_external_data', ['external_id'], unique=True)
    op.create_index(op.f('ix_ftth_external_data_id'), 'ftth_external_data', ['id'], unique=False)
    op.create_index(op.f('ix_ftth_external_data_imported_subscriber_id'), 'ftth_external_data', ['imported_subscriber_id'], unique=False)
    op.create_table('internet_fats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['internet_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internet_fats_id'), 'internet_fats', ['id'], unique=False)
    op.create_index(op.f('ix_internet_fats_zone_id'), 'internet_fats', ['zone_id'], unique=False)
    op.create_table('internet_material_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('subscriber_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['internet_materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internet_material_sales_id'), 'internet_material_sales', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('office_customer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['office_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_customer_history_id'), 'office_customer_history', ['id'], unique=False)
    op.create_table('office_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=True),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['office_customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_invoices_customer_id'), 'office_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_office_invoices_id'), 'office_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_office_invoices_invoice_no'), 'office_invoices', ['invoice_no'], unique=True)
    op.create_table('office_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('installment_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['office_customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_payments_customer_id'), 'office_payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_office_payments_id'), 'office_payments', ['id'], unique=False)
    op.create_table('office_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_with_commission', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('installments_months', sa.Integer(), nullable=True),
    sa.Column('monthly_installment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['office_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['office_materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_sales_id'), 'office_sales', ['id'], unique=False)
    op.create_table('partner_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('partner_share', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_transactions_id'), 'partner_transactions', ['id'], unique=False)
    op.create_table('sim_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['sim_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_sim_numbers_id'), 'sim_numbers', ['id'], unique=False)
    op.create_table('subscriber_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_history_id'), 'subscriber_history', ['id'], unique=False)
    op.create_table('supplier_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_transactions_id'), 'supplier_transactions', ['id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.BigInteger(), nullable=True),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_subscriber_id'), 'telegram_users', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_telegram_users_telegram_chat_id'), 'telegram_users', ['telegram_chat_id'], unique=True)
    op.create_table('office_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('installment_index', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['office_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['office_sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_installments_customer_id'), 'office_installments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_office_installments_id'), 'office_installments', ['id'], unique=False)
    op.create_table('office_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['office_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['office_materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_invoice_items_id'), 'office_invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_office_invoice_items_invoice_id'), 'office_invoice_items', ['invoice_id'], unique=False)
    op.create_table('sim_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('company_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('jb_return', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sim_number_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['sim_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sim_number_id'], ['sim_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_sales_id'), 'sim_sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_sales_id'), table_name='sim_sales')
    op.drop_table('sim_sales')
    op.drop_index(op.f('ix_office_invoice_items_invoice_id'), table_name='office_invoice_items')
    op.drop_index(op.f('ix_office_invoice_items_id'), table_name='office_invoice_items')
    op.drop_table('office_invoice_items')
    op.drop_index(op.f('ix_office_installments_id'), table_name='office_installments')
    op.drop_index(op.f('ix_office_installments_customer_id'), table_name='office_installments')
    op.drop_table('office_installments')
    op.drop_index(op.f('ix_telegram_users_telegram_chat_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_subscriber_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_supplier_transactions_id'), table_name='supplier_transactions')
    op.drop_table('supplier_transactions')
    op.drop_index(op.f('ix_subscriber_history_id'), table_name='subscriber_history')
    op.drop_table('subscriber_history')
    op.drop_index(op.f('ix_sim_numbers_id'), table_name='sim_numbers')
    op.drop_table('sim_numbers')
    op.drop_index(op.f('ix_partner_transactions_id'), table_name='partner_transactions')
    op.drop_table('partner_transactions')
    op.drop_index(op.f('ix_office_sales_id'), table_name='office_sales')
    op.drop_table('office_sales')
    op.drop_index(op.f('ix_office_payments_id'), table_name='office_payments')
    op.drop_index(op.f('ix_office_payments_customer_id'), table_name='office_payments')
    op.drop_table('office_payments')
    op.drop_index(op.f('ix_office_invoices_invoice_no'), table_name='office_invoices')
    op.drop_index(op.f('ix_office_invoices_id'), table_name='office_invoices')
    op.drop_index(op.f('ix_office_invoices_customer_id'), table_name='office_invoices')
    op.drop_table('office_invoices')
    op.drop_index(op.f('ix_office_customer_history_id'), table_name='office_customer_history')
    op.drop_table('office_customer_history')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_internet_material_sales_id'), table_name='internet_material_sales')
    op.drop_table('internet_material_sales')
    op.drop_index(op.f('ix_internet_fats_zone_id'), table_name='internet_fats')
    op.drop_index(op.f('ix_internet_fats_id'), table_name='internet_fats')
    op.drop_table('internet_fats')
    op.drop_index(op.f('ix_ftth_external_data_imported_subscriber_id'), table_name='ftth_external_data')
    op.drop_index(op.f('ix_ftth_external_data_id'), table_name='ftth_external_data')
    op.drop_index(op.f('ix_ftth_external_data_external_id'), table_name='ftth_external_data')
    op.drop_table('ftth_external_data')
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_subscription_categories_id'), table_name='subscription_categories')
    op.drop_table('subscription_categories')
    op.drop_index(op.f('ix_subscribers_user_code'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_telegram_chat_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_sim_packages_id'), table_name='sim_packages')
    op.drop_table('sim_packages')
    op.drop_index(op.f('ix_sim_inventory_transactions_id'), table_name='sim_inventory_transactions')
    op.drop_table('sim_inventory_transactions')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_office_materials_id'), table_name='office_materials')
    op.drop_table('office_materials')
    op.drop_index(op.f('ix_office_customers_id'), table_name='office_customers')
    op.drop_table('office_customers')
    op.drop_index(op.f('ix_internet_zones_id'), table_name='internet_zones')
    op.drop_table('internet_zones')
    op.drop_index(op.f('ix_internet_phones_phone_number'), table_name='internet_phones')
    op.drop_index(op.f('ix_internet_phones_id'), table_name='internet_phones')
    op.drop_table('internet_phones')
    op.drop_index(op.f('ix_internet_materials_id'), table_name='internet_materials')
    op.drop_table('internet_materials')
    op.drop_index(op.f('ix_ftth_portal_config_id'), table_name='ftth_portal_config')
    op.drop_table('ftth_portal_config')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_cashback_history_id'), table_name='cashback_history')
    op.drop_table('cashback_history')
    op.drop_index(op.f('ix_card_wallet_transactions_id'), table_name='card_wallet_transactions')
    op.drop_table('card_wallet_transactions')
    op.drop_index(op.f('ix_card_sales_id'), table_name='card_sales')
    op.drop_table('card_sales')
    op.drop_index(op.f('ix_card_purchases_id'), table_name='card_purchases')
    op.drop_table('card_purchases')
    # ### end Alembic commands ###
