"""Add broadcast queue and status tracking

Revision ID: e514ab602879
Revises: 20bb3b17bc42
Create Date: 2026-04-07 17:48:11.557626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e514ab602879'
down_revision: Union[str, None] = '20bb3b17bc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_queue_id'), 'broadcast_queue', ['id'], unique=False)
    op.create_index(op.f('ix_broadcast_queue_recipient'), 'broadcast_queue', ['recipient'], unique=False)
    op.create_index(op.f('ix_broadcast_queue_scheduled_at'), 'broadcast_queue', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_broadcast_queue_status'), 'broadcast_queue', ['status'], unique=False)
    op.add_column('subscribers', sa.Column('last_debt_alert_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'last_debt_alert_sent')
    op.drop_index(op.f('ix_broadcast_queue_status'), table_name='broadcast_queue')
    op.drop_index(op.f('ix_broadcast_queue_scheduled_at'), table_name='broadcast_queue')
    op.drop_index(op.f('ix_broadcast_queue_recipient'), table_name='broadcast_queue')
    op.drop_index(op.f('ix_broadcast_queue_id'), table_name='broadcast_queue')
    op.drop_table('broadcast_queue')
    # ### end Alembic commands ###
